### ISSUE TITLE
Does this work when installing from the lockfile?

### ISSUE THREAD

**Issue by chris-hinds** [SocialGouv/yarn-workspace-focus-install#289]
The suggest that using --frozen-lockfile doesn't work. However looking at your tests it looks like running 

```
npx @socialgouv/yarn-workspace-focus-install --cwd packages/api-ppi --frozen-lockfile
``` 
may actually work.

However this doesn't work in practice, i get the following error

```
Error: Command failed with exit code 1: yarn --frozen-lockfile
    at makeError (/Users/chinds/.npm/_npx/61317/lib/node_modules/@socialgouv/yarn-workspace-focus-install/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/chinds/.npm/_npx/61317/lib/node_modules/@socialgouv/yarn-workspace-focus-install/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.focusInstall (/Users/chinds/.npm/_npx/61317/lib/node_modules/@socialgouv/yarn-workspace-focus-install/lib/install.js:47:5) {
  shortMessage: 'Command failed with exit code 1: yarn --frozen-lockfile',
  command: 'yarn --frozen-lockfile',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by douglasduteil** [comment]
Hi @chris-hinds 

Yes.
You can pass any arguments to yarn through `--`

```sh
$ npx @socialgouv/yarn-workspace-focus-install --cwd packages/api-ppi -- --frozen-lockfile
```

see https://github.com/SocialGouv/yarn-workspace-focus-install#usage

Note that this flag is already [default](https://github.com/SocialGouv/yarn-workspace-focus-install/blob/master/src/yarn.ts#L19)
https://github.com/SocialGouv/yarn-workspace-focus-install/blob/81083fd07f5a00299568a22a1e647d8f832e105f/src/yarn.ts#L19
